"""init

Revision ID: 1267b2093717
Revises: 
Create Date: 2026-02-05 11:20:31.154793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1267b2093717'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('middle_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('object_id', sa.BigInteger(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('ADMIN', 'ACCOUNTANT', 'HR', 'ENGINEER', 'LAWYER', 'EMPLOYEE', name='userrole', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_users_department'), 'users', ['department'], unique=False)
    op.create_index(op.f('ix_users_object_id'), 'users', ['object_id'], unique=False)
    op.create_index(op.f('ix_users_position'), 'users', ['position'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_position'), table_name='users')
    op.drop_index(op.f('ix_users_object_id'), table_name='users')
    op.drop_index(op.f('ix_users_department'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'ACCOUNTANT', 'HR', 'ENGINEER', 'LAWYER', 'EMPLOYEE', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_column('users', 'object_id')
    op.drop_column('users', 'location')
    op.drop_column('users', 'position')
    op.drop_column('users', 'department')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
