"""Add access_departments to ObjectAccess

Revision ID: 2f0480f9b25a
Revises: fbde1dcb4e08
Create Date: 2026-02-13 10:45:18.803535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0480f9b25a'
down_revision: Union[str, Sequence[str], None] = 'fbde1dcb4e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_accesses', sa.Column('access_departments', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_accesses', 'access_departments')
    # ### end Alembic commands ###
