"""Add documents table with categories

Revision ID: 39753a8a5f13
Revises: 1267b2093717
Create Date: 2026-02-06 16:54:30.404303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39753a8a5f13'
down_revision: Union[str, Sequence[str], None] = '1267b2093717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_object_accesses_object_user'), table_name='object_accesses')
    op.drop_index(op.f('ix_object_accesses_user_id'), table_name='object_accesses')
    op.drop_table('object_accesses')
    op.drop_index(op.f('ix_objects_created_by'), table_name='objects')
    op.drop_index(op.f('ix_objects_department'), table_name='objects')
    op.drop_index(op.f('ix_objects_department_location'), table_name='objects')
    op.drop_index(op.f('ix_objects_id'), table_name='objects')
    op.drop_index(op.f('ix_objects_is_active'), table_name='objects')
    op.drop_index(op.f('ix_objects_location'), table_name='objects')
    op.drop_index(op.f('ix_objects_title'), table_name='objects')
    op.drop_table('objects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('objects_created_by_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('objects_updated_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('objects_pkey'))
    )
    op.create_index(op.f('ix_objects_title'), 'objects', ['title'], unique=False)
    op.create_index(op.f('ix_objects_location'), 'objects', ['location'], unique=False)
    op.create_index(op.f('ix_objects_is_active'), 'objects', ['is_active'], unique=False)
    op.create_index(op.f('ix_objects_id'), 'objects', ['id'], unique=False)
    op.create_index(op.f('ix_objects_department_location'), 'objects', ['department', 'location'], unique=False)
    op.create_index(op.f('ix_objects_department'), 'objects', ['department'], unique=False)
    op.create_index(op.f('ix_objects_created_by'), 'objects', ['created_by'], unique=False)
    op.create_table('object_accesses',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('granted_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('object_accesses_granted_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], name=op.f('object_accesses_object_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('object_accesses_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('object_accesses_pkey'))
    )
    op.create_index(op.f('ix_object_accesses_user_id'), 'object_accesses', ['user_id'], unique=False)
    op.create_index(op.f('ix_object_accesses_object_user'), 'object_accesses', ['object_id', 'user_id'], unique=True)
    # ### end Alembic commands ###
