"""Add document subcategories table

Revision ID: 4befafe22052
Revises: 116918c8d089
Create Date: 2026-02-09 19:14:32.195929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4befafe22052'
down_revision: Union[str, Sequence[str], None] = '116918c8d089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_subcategories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('GENERAL', 'ACCOUNTING', 'SAFETY', 'TECHNICAL', 'LEGAL', 'HR', name='documentcategory', native_enum=False), nullable=False),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_subcategories_category'), 'document_subcategories', ['category'], unique=False)
    op.create_index(op.f('ix_document_subcategories_id'), 'document_subcategories', ['id'], unique=False)
    op.create_index('ix_subcategory_object', 'document_subcategories', ['object_id'], unique=False)
    op.create_index('ix_subcategory_object_category', 'document_subcategories', ['object_id', 'category'], unique=False)
    op.add_column('documents', sa.Column('subcategory_id', sa.BigInteger(), nullable=True))
    op.drop_index(op.f('ix_documents_created_by'), table_name='documents')
    op.create_index('ix_documents_subcategory_id', 'documents', ['subcategory_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'document_subcategories', ['subcategory_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_objects_created_by'), table_name='objects')
    op.drop_index(op.f('ix_objects_is_active'), table_name='objects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_objects_is_active'), 'objects', ['is_active'], unique=False)
    op.create_index(op.f('ix_objects_created_by'), 'objects', ['created_by'], unique=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index('ix_documents_subcategory_id', table_name='documents')
    op.create_index(op.f('ix_documents_created_by'), 'documents', ['created_by'], unique=False)
    op.drop_column('documents', 'subcategory_id')
    op.drop_index('ix_subcategory_object_category', table_name='document_subcategories')
    op.drop_index('ix_subcategory_object', table_name='document_subcategories')
    op.drop_index(op.f('ix_document_subcategories_id'), table_name='document_subcategories')
    op.drop_index(op.f('ix_document_subcategories_category'), table_name='document_subcategories')
    op.drop_table('document_subcategories')
    # ### end Alembic commands ###
