"""initial_migration

Revision ID: 5700b245002e
Revises:
Create Date: 2026-03-03 11:35:14.778981

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5700b245002e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="alertseverity",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum(
                "SECURITY_EVENT",
                "MULTIPLE_FAILED_LOGINS",
                "SUSPICIOUS_IP",
                "SYSTEM_ERROR",
                "CUSTOM",
                name="alerttype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alerts_ip_address"), "alerts", ["ip_address"], unique=False
    )
    op.create_index(op.f("ix_alerts_resolved"), "alerts", ["resolved"], unique=False)
    op.create_index(op.f("ix_alerts_severity"), "alerts", ["severity"], unique=False)
    op.create_index(op.f("ix_alerts_timestamp"), "alerts", ["timestamp"], unique=False)
    op.create_index(op.f("ix_alerts_type"), "alerts", ["type"], unique=False)
    op.create_index(op.f("ix_alerts_user_id"), "alerts", ["user_id"], unique=False)
    op.create_table(
        "departments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_departments_id"), "departments", ["id"], unique=False)
    op.create_index(op.f("ix_departments_name"), "departments", ["name"], unique=True)
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_login_attempts_email"), "login_attempts", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_login_attempts_ip_address"),
        "login_attempts",
        ["ip_address"],
        unique=False,
    )
    op.create_table(
        "user_agent_cache",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_agent"),
    )
    op.create_index(
        op.f("ix_user_agent_cache_id"), "user_agent_cache", ["id"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=True),
        sa.Column("trace_id", sa.String(length=36), nullable=True),
        sa.Column(
            "level",
            sa.Enum(
                "DEBUG",
                "INFO",
                "WARNING",
                "ERROR",
                "CRITICAL",
                name="loglevel",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("event", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("user_email", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent_id", sa.BigInteger(), nullable=True),
        sa.Column("http_method", sa.String(length=10), nullable=True),
        sa.Column("http_path", sa.String(length=512), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_agent_id"],
            ["user_agent_cache.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_duration_ms"), "audit_logs", ["duration_ms"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_event"), "audit_logs", ["event"], unique=False)
    op.create_index(
        "ix_audit_logs_event_created",
        "audit_logs",
        ["event", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_expires",
        "audit_logs",
        ["expires_at", "is_archived"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_expires_at"), "audit_logs", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_http_method"), "audit_logs", ["http_method"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_http_path"), "audit_logs", ["http_path"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_http_status"), "audit_logs", ["http_status"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_ip_address"), "audit_logs", ["ip_address"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_is_archived"), "audit_logs", ["is_archived"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_level"), "audit_logs", ["level"], unique=False)
    op.create_index(
        "ix_audit_logs_level_created",
        "audit_logs",
        ["level", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_status_created",
        "audit_logs",
        ["http_status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_trace_id"), "audit_logs", ["trace_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_user_agent_id"),
        "audit_logs",
        ["user_agent_id"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_user_created",
        "audit_logs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_user_email"), "audit_logs", ["user_email"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN",
                "ACCOUNTANT",
                "HR",
                "ENGINEER",
                "LAWYER",
                "SAFETY",
                "EMPLOYEE",
                name="userrole",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("middle_name", sa.String(length=255), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("department_id", sa.BigInteger(), nullable=True),
        sa.Column("position", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("object_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_index(
        op.f("ix_users_activated_at"), "users", ["activated_at"], unique=False
    )
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_users_department_id"), "users", ["department_id"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        "ix_users_email_lower",
        "users",
        [sa.literal_column("lower(email)")],
        unique=True,
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_object_id"), "users", ["object_id"], unique=False)
    op.create_index(op.f("ix_users_position"), "users", ["position"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "objects",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon_url", sa.String(length=500), nullable=True),
        sa.Column("department", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_objects_department"), "objects", ["department"], unique=False
    )
    op.create_index(
        "ix_objects_department_location",
        "objects",
        ["department", "location"],
        unique=False,
    )
    op.create_index(op.f("ix_objects_id"), "objects", ["id"], unique=False)
    op.create_index(op.f("ix_objects_location"), "objects", ["location"], unique=False)
    op.create_index(op.f("ix_objects_title"), "objects", ["title"], unique=False)
    op.create_table(
        "otp_codes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "LOGIN",
                "EMAIL_VERIFY",
                "PASSWORD_RESET",
                name="otppurpose",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_otp_expires_at", "otp_codes", ["expires_at"], unique=False)
    op.create_index(
        "ix_otp_user_purpose", "otp_codes", ["user_id", "purpose"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=False
    )
    op.create_table(
        "document_subcategories",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "GENERAL",
                "ACCOUNTING",
                "SAFETY",
                "TECHNICAL",
                "LEGAL",
                "HR",
                name="documentcategory",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("object_id", sa.BigInteger(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_subcategories_category"),
        "document_subcategories",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_subcategories_id"),
        "document_subcategories",
        ["id"],
        unique=False,
    )
    op.create_index(
        "ix_subcategory_object", "document_subcategories", ["object_id"], unique=False
    )
    op.create_index(
        "ix_subcategory_object_category",
        "document_subcategories",
        ["object_id", "category"],
        unique=False,
    )
    op.create_table(
        "object_accesses",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("object_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("access_departments", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "ADMIN",
                "EDITOR",
                "VIEWER",
                name="objectaccessrole",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "sections_access",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Список разделов документов, к которым есть доступ",
        ),
        sa.Column("granted_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["granted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_object_accesses_id"), "object_accesses", ["id"], unique=False
    )
    op.create_index(
        "ix_object_accesses_object_user",
        "object_accesses",
        ["object_id", "user_id"],
        unique=True,
    )
    op.create_index(
        "ix_object_accesses_user_id", "object_accesses", ["user_id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "GENERAL",
                "ACCOUNTING",
                "SAFETY",
                "TECHNICAL",
                "LEGAL",
                "HR",
                name="documentcategory",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("subcategory_id", sa.BigInteger(), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("file_type", sa.String(length=100), nullable=True),
        sa.Column("object_id", sa.BigInteger(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["subcategory_id"], ["document_subcategories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documents_category"), "documents", ["category"], unique=False
    )
    op.create_index(op.f("ix_documents_id"), "documents", ["id"], unique=False)
    op.create_index(
        "ix_documents_object_category",
        "documents",
        ["object_id", "category"],
        unique=False,
    )
    op.create_index("ix_documents_object_id", "documents", ["object_id"], unique=False)
    op.create_index(
        "ix_documents_subcategory_id", "documents", ["subcategory_id"], unique=False
    )
    op.create_index(op.f("ix_documents_title"), "documents", ["title"], unique=False)

    op.create_table(
        "acls",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("role", sa.String(length=10), nullable=True),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("object_id", sa.Integer(), nullable=True),
        sa.Column("permission", sa.String(length=6), nullable=False),
        sa.Column(
            "effect", sa.String(length=5), nullable=False, server_default="allow"
        ),
        sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("granted_by", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.create_index("ix_acls_resource", "acls", ["resource_type", "resource_id"])
    op.create_index("ix_acls_user", "acls", ["user_id"])
    op.create_index("ix_acls_role", "acls", ["role"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_title"), table_name="documents")
    op.drop_index("ix_documents_subcategory_id", table_name="documents")
    op.drop_index("ix_documents_object_id", table_name="documents")
    op.drop_index("ix_documents_object_category", table_name="documents")
    op.drop_index(op.f("ix_documents_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_category"), table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_object_accesses_user_id", table_name="object_accesses")
    op.drop_index("ix_object_accesses_object_user", table_name="object_accesses")
    op.drop_index(op.f("ix_object_accesses_id"), table_name="object_accesses")
    op.drop_table("object_accesses")
    op.drop_index("ix_subcategory_object_category", table_name="document_subcategories")
    op.drop_index("ix_subcategory_object", table_name="document_subcategories")
    op.drop_index(
        op.f("ix_document_subcategories_id"), table_name="document_subcategories"
    )
    op.drop_index(
        op.f("ix_document_subcategories_category"), table_name="document_subcategories"
    )
    op.drop_table("document_subcategories")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_otp_user_purpose", table_name="otp_codes")
    op.drop_index("ix_otp_expires_at", table_name="otp_codes")
    op.drop_table("otp_codes")
    op.drop_index(op.f("ix_objects_title"), table_name="objects")
    op.drop_index(op.f("ix_objects_location"), table_name="objects")
    op.drop_index(op.f("ix_objects_id"), table_name="objects")
    op.drop_index("ix_objects_department_location", table_name="objects")
    op.drop_index(op.f("ix_objects_department"), table_name="objects")
    op.drop_table("objects")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_position"), table_name="users")
    op.drop_index(op.f("ix_users_object_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index("ix_users_email_lower", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_department_id"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_index(op.f("ix_users_activated_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_user_email"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_user_created", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_user_agent_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_trace_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_status_created", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_request_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_level_created", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_level"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_is_archived"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_ip_address"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_http_status"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_http_path"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_http_method"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_expires_at"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_expires", table_name="audit_logs")
    op.drop_index("ix_audit_logs_event_created", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_event"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_duration_ms"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_user_agent_cache_id"), table_name="user_agent_cache")
    op.drop_table("user_agent_cache")
    op.drop_index(op.f("ix_login_attempts_ip_address"), table_name="login_attempts")
    op.drop_index(op.f("ix_login_attempts_email"), table_name="login_attempts")
    op.drop_table("login_attempts")
    op.drop_index(op.f("ix_departments_name"), table_name="departments")
    op.drop_index(op.f("ix_departments_id"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_alerts_user_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_type"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_timestamp"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_severity"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_resolved"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_ip_address"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("ix_acls_role", table_name="acls")
    op.drop_index("ix_acls_user", table_name="acls")
    op.drop_index("ix_acls_resource", table_name="acls")
    op.drop_table("acls")
    # ### end Alembic commands ###
