"""Add objects and documents tables

Revision ID: 608e15abed42
Revises: 39753a8a5f13
Create Date: 2026-02-06 17:28:14.743636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608e15abed42'
down_revision: Union[str, Sequence[str], None] = '39753a8a5f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_objects_created_by', 'objects', ['created_by'], unique=False)
    op.create_index(op.f('ix_objects_department'), 'objects', ['department'], unique=False)
    op.create_index('ix_objects_department_location', 'objects', ['department', 'location'], unique=False)
    op.create_index(op.f('ix_objects_id'), 'objects', ['id'], unique=False)
    op.create_index('ix_objects_is_active', 'objects', ['is_active'], unique=False)
    op.create_index(op.f('ix_objects_location'), 'objects', ['location'], unique=False)
    op.create_index(op.f('ix_objects_title'), 'objects', ['title'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('GENERAL', 'ACCOUNTING', 'SAFETY', 'TECHNICAL', 'LEGAL', 'HR', name='documentcategory', native_enum=False), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index('ix_documents_created_by', 'documents', ['created_by'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index('ix_documents_object_category', 'documents', ['object_id', 'category'], unique=False)
    op.create_index(op.f('ix_documents_object_id'), 'documents', ['object_id'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_table('object_accesses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'EDITOR', 'ADMIN', 'OWNER', name='objectaccessrole', native_enum=False), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_object_accesses_object_user', 'object_accesses', ['object_id', 'user_id'], unique=True)
    op.create_index('ix_object_accesses_user_id', 'object_accesses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_object_accesses_user_id', table_name='object_accesses')
    op.drop_index('ix_object_accesses_object_user', table_name='object_accesses')
    op.drop_table('object_accesses')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_object_id'), table_name='documents')
    op.drop_index('ix_documents_object_category', table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index('ix_documents_created_by', table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_objects_title'), table_name='objects')
    op.drop_index(op.f('ix_objects_location'), table_name='objects')
    op.drop_index('ix_objects_is_active', table_name='objects')
    op.drop_index(op.f('ix_objects_id'), table_name='objects')
    op.drop_index('ix_objects_department_location', table_name='objects')
    op.drop_index(op.f('ix_objects_department'), table_name='objects')
    op.drop_index('ix_objects_created_by', table_name='objects')
    op.drop_table('objects')
    # ### end Alembic commands ###
