"""init schema

Revision ID: 68743a5969a0
Revises: 
Create Date: 2026-03-02 13:27:49.595208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68743a5969a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acls_resource'), table_name='acls')
    op.drop_index(op.f('ix_acls_role'), table_name='acls')
    op.drop_index(op.f('ix_acls_user'), table_name='acls')
    op.drop_table('acls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permission', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('effect', sa.VARCHAR(length=5), server_default=sa.text("'allow'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('granted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('acls_created_by_fkey')),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('acls_granted_by_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('acls_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('acls_pkey'))
    )
    op.create_index(op.f('ix_acls_user'), 'acls', ['user_id'], unique=False)
    op.create_index(op.f('ix_acls_role'), 'acls', ['role'], unique=False)
    op.create_index(op.f('ix_acls_resource'), 'acls', ['resource_type', 'resource_id'], unique=False)
    # ### end Alembic commands ###
