"""Add activated_at to users

Revision ID: e1d21fec95a2
Revises: e2edf096d15b
Create Date: 2026-02-11 17:20:51.231514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1d21fec95a2'
down_revision: Union[str, Sequence[str], None] = 'e2edf096d15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_activated_at'), 'users', ['activated_at'], unique=False)
    op.drop_column('users', 'delete_att')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delete_att', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_activated_at'), table_name='users')
    op.drop_column('users', 'activated_at')
    # ### end Alembic commands ###
