"""Add deleted_at to users

Revision ID: e2edf096d15b
Revises: 4befafe22052
Create Date: 2026-02-11 16:00:24.715916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2edf096d15b'
down_revision: Union[str, Sequence[str], None] = '4befafe22052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delete_att', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_delete_att'), 'users', ['delete_att'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_delete_att'), table_name='users')
    op.drop_column('users', 'delete_att')
    # ### end Alembic commands ###
