"""Add audit_logs and user_agent_cache tables

Revision ID: fbde1dcb4e08
Revises: 474ff0385537
Create Date: 2026-02-12 15:09:04.702211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbde1dcb4e08'
down_revision: Union[str, Sequence[str], None] = '474ff0385537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_agent_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_agent')
    )
    op.create_index(op.f('ix_user_agent_cache_id'), 'user_agent_cache', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel', native_enum=False), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent_id', sa.BigInteger(), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('http_path', sa.String(length=512), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_agent_id'], ['user_agent_cache.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_duration_ms'), 'audit_logs', ['duration_ms'], unique=False)
    op.create_index(op.f('ix_audit_logs_event'), 'audit_logs', ['event'], unique=False)
    op.create_index('ix_audit_logs_event_created', 'audit_logs', ['event', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_expires', 'audit_logs', ['expires_at', 'is_archived'], unique=False)
    op.create_index(op.f('ix_audit_logs_expires_at'), 'audit_logs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_http_method'), 'audit_logs', ['http_method'], unique=False)
    op.create_index(op.f('ix_audit_logs_http_path'), 'audit_logs', ['http_path'], unique=False)
    op.create_index(op.f('ix_audit_logs_http_status'), 'audit_logs', ['http_status'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_archived'), 'audit_logs', ['is_archived'], unique=False)
    op.create_index(op.f('ix_audit_logs_level'), 'audit_logs', ['level'], unique=False)
    op.create_index('ix_audit_logs_level_created', 'audit_logs', ['level', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_request_id', 'audit_logs', ['request_id'], unique=False)
    op.create_index('ix_audit_logs_status_created', 'audit_logs', ['http_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_trace_id'), 'audit_logs', ['trace_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_agent_id'), 'audit_logs', ['user_agent_id'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_email'), 'audit_logs', ['user_email'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_email'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_agent_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_trace_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_status_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_request_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_level_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_level'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_archived'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_http_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_http_path'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_http_method'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_expires_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_expires', table_name='audit_logs')
    op.drop_index('ix_audit_logs_event_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_duration_ms'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_user_agent_cache_id'), table_name='user_agent_cache')
    op.drop_table('user_agent_cache')
    # ### end Alembic commands ###
