version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: employees_redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "6379:6379"
    networks:
      redis_shared:
        aliases:
          - shared-redis
          - redis

  backend:
    build: .
    container_name: employees_app
    restart: always
    env_file: .env
    environment:
      - TZ=Europe/Moscow
      - DATABASE_URL=${DATABASE_URL}
      - FILES_PATH=/app/files
    command: >
      sh -c "
        alembic upgrade head &&
        exec gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --preload
      "
    ports:
      - "8001:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - redis_shared
    volumes:
      - ./app/alembic.ini:/app/alembic.ini
      - ./app/migrations:/app/migrations
      - ./app/main.py:/app/main.py
      - ./app/core:/app/core
      - ./app/modules:/app/modules
      - ./app/services:/app/services
      - ./app/static:/app/static
      - ./app/templates:/app/templates
      - ./app/workers:/app/workers
      - ./logs:/app/logs
      - /volume11/projects/employe_cabinet/files:/app/files

networks:
  redis_shared:
    external: true
    name: redis_network
